const mongoose = require("mongoose");

const rankingsSchema = new mongoose.Schema({
  // Ranking type (scripts, projects, creators)
  type: {
    type: String,
    enum: ['scripts', 'projects', 'creators'],
    required: true
  },

  // Ranking period
  period: {
    type: String,
    enum: ['weekly', 'monthly', 'all-time'],
    required: true
  },

  // Rankings data
  rankings: [{
    itemId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      refPath: 'rankings.itemModel'
    },
    itemModel: {
      type: String,
      required: true,
      enum: ['Script', 'Project', 'User']
    },
    rank: {
      type: Number,
      required: true,
      min: 1
    },
    score: {
      type: Number,
      required: true,
      default: 0
    },
    previousRank: {
      type: Number,
      default: null
    },
    change: {
      type: Number,
      default: 0 // positive = up, negative = down
    },
    metadata: {
      title: String,
      author: String,
      views: Number,
      likes: Number,
      rating: Number
    }
  }],

  // Ranking date
  date: {
    type: Date,
    default: Date.now
  },

  // Auto-generated flag
  isAutoGenerated: {
    type: Boolean,
    default: true
  },

  // Manual override flag
  isManualOverride: {
    type: Boolean,
    default: false
  },

  // Admin who created/updated
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// Compound index for efficient queries
rankingsSchema.index({ type: 1, period: 1, date: -1 });

// Method to get current rankings
rankingsSchema.statics.getCurrentRankings = function(type, period) {
  return this.findOne({ type, period })
    .sort({ date: -1 })
    .populate('rankings.itemId', 'name title email');
};

// Method to update rankings
rankingsSchema.statics.updateRankings = async function(type, period, newRankings, adminId = null) {
  const ranking = new this({
    type,
    period,
    rankings: newRankings,
    updatedBy: adminId,
    isAutoGenerated: !adminId
  });

  await ranking.save();
  return ranking;
};

module.exports = mongoose.model("Rankings", rankingsSchema);
